### ISSUE TITLE
Making values class properties instead of returning them in a function

### ISSUE THREAD

**Issue by antonsamper** [cornflourblue/angular2-pagination-example#4]
Hi Jason (@cornflourblue), I recently came across this service you had written and really liked it so i decided to include it in my project, however, i decided to refactor some of the code and change the service API. One of the key things i did was to change the pager function so that instead of returning the pager properties:
```
// return object with all pager properties required by the view
return {
    totalItems: totalItems,
    currentPage: currentPage,
    ...
};
```

It would instead assign the  pager values to the class:
```
this.totalItems = totalItems;
this.currentPage = currentPage;
...
```

Thus turning this stateless service into a stateful one.

This makes sense for my current app as I want to keep track of what page the user is on even after they switch routes i.e. incase they return to the results page.

Was there any particular reason why you made this service stateless?

**Comment by cornflourblue** [comment]
Hi Anton, a service method returning an object feels more natural to me, storing state in the pager service could cause issues if you have more than one section in your app that uses paging, because the service doesn't know what it's paging but simply calculating some numbers based on the input parameters.

I'd suggest maybe storing the return object from the pager service somewhere else along with the name/id of the section it's for.

**Comment by antonsamper** [comment]
Hi Jason, i hadn't thought about multiple pagination components as i don't need them on my particular project but you're right, storing  the pager results on a separate service might be the answer and that way the pagination component will be reusable.
